[package]
name = "ya0201ctl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
