name: Trigger Homebrew Tap Update

on:
  release:
    types: [created, published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get asset URLs
        id: get_urls
        run: |
          assets='${{ toJson(github.event.release.assets) }}'
          macos_url=$(echo "$assets" | jq -r '.[] | select(.name == "ya0201ctl-macos.tar.gz") | .browser_download_url')
          linux_url=$(echo "$assets" | jq -r '.[] | select(.name == "ya0201ctl-linux.tar.gz") | .browser_download_url')
          echo "macos_url=$macos_url" >> $GITHUB_OUTPUT
          echo "linux_url=$linux_url" >> $GITHUB_OUTPUT

      - name: Dispatch to tap repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TAP_PAT }}" \
            https://api.github.com/repos/ya0201/homebrew-ya0201ctl/actions/workflows/update-formula.yml/dispatches \
            -d @- <<EOF
          {
            "ref": "main",
            "inputs": {
              "tag": "${{ github.event.release.tag_name }}",
              "macos_url": "${{ steps.get_urls.outputs.macos_url }}",
              "linux_url": "${{ steps.get_urls.outputs.linux_url }}"
            }
          }
          EOF
